server:
  port: ${PORT:8080}
spring:
  application:
    name: healthsystemapi
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/healthsystem}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  default-admin:
    username: ${DEFAULT_ADMIN_USERNAME:admin}
    password: ${DEFAULT_ADMIN_PASSWORD:admin}
  default-user-password: ${DEFAULT_USER_PASSWORD}
  default-employee-password: ${DEFAULT_EMPLOYEE_PASSWORD}
security:
  refresh:
    expiration: 604800000
#    expiration: 60000
  access:
    expiration: 900000
#    expiration: 30000
